# Generated by Django 4.2.7 on 2023-11-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_question_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
    ]
