# Generated by Django 4.2.7 on 2023-11-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_answer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
