# Generated by Django 4.2.7 on 2023-11-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_answer_date_alter_question_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
